@startuml
title Activité — Créer une déclaration (avant sauvegarde)

start

partition Declarant {
  :Créer une DeclarationVehicule (non sauvegardée);
  :Renseigner infos (vol + véhicule);
  :dateCreation = now;
  :dateDerniereModif = now;

  while (Modifier avant sauvegarde ?) is (oui)
    :editer(nouvellesInfos);
    :dateDerniereModif = now;
  endwhile (non)

  if (Supprimer avant sauvegarde ?) then (oui)
    :Annuler la déclaration;
    stop
  else (non)
    :validerSauvegarde();
  endif
}

partition GestionnaireSysteme {
  :creerDeclaration(declaration, declarant);
  :attribuerId();
  :Confirmation sauvegarde;
}

stop
@enduml
