@startuml
title Séquence — Créer une déclaration (avant sauvegarde → sauvegarde)

actor Declarant as declarant

participant GestionnaireSysteme as gs
participant "DeclarationVehicule" as declV

declarant -> gs : creerDeclaration(declV, declarant)
activate gs

gs -> declV : initialiser(infosVol, lieuVol,\nmarque, couleur, description,\nmatricule, modele, roleDeclarant)
activate declV
note right of declV
dateCreation = now
dateDerniereModif = now
end note
deactivate declV

loop Tant que le déclarant modifie avant sauvegarde
  declarant -> declV : editer(nouvellesInfos)
  note right of declV
  dateDerniereModif = now
  end note
end

alt Suppression avant sauvegarde
  declarant -> gs : supprimerDeclaration(declV)
  gs -> declV : supprimer()
  destroy declV
  gs --> declarant : confirmationSuppression()
else Sauvegarde
  declarant -> declV : validerSauvegarde()
  gs -> declV : attribuerId()
  gs --> declarant : confirmationSauvegarde(id)
end

deactivate gs
@enduml
