@startuml
title Séquence — Agent met à jour l’état d’une déclaration (véhicule retrouvé)

actor AgentPolicier as agent

participant GestionnaireSysteme as gs
participant "declaration : DeclarationVehicule" as decl

agent -> gs : sAuthentifier(matricule, motDePasse)
activate gs

alt Authentification OK
  gs --> agent : true

  agent -> gs : mettreAJourEtatDeclaration(idDeclaration, RESOLUE)
  gs -> gs : rechercherDeclaration(idDeclaration)

  gs -> decl : setEtat(RESOLUE)
  activate decl
  gs -> decl : setDateResolution(now)
  note right of decl
  etat = RESOLUE
  dateResolution = now
  dateDerniereModif = now
  end note
  gs -> decl : setDateDerniereModif(now)
  deactivate decl

  gs --> agent : confirmationMiseAJour()
else Authentification KO
  gs --> agent : false
end

deactivate gs
@enduml
