@startuml
left to right direction
skinparam packageStyle rectangle
skinparam shadow false
skinparam linetype polyline

' --- STYLES ---
skinparam actor {
    BackgroundColor White
    BorderColor Black
}
skinparam usecase {
    BackgroundColor White
    BorderColor Black
}

' Acteurs Publics (Verts)
skinparam actor<<Public>> {
    BorderColor #1ABC9C
    FontColor #1ABC9C
    BackgroundColor #E8F8F5
}
skinparam usecase<<Public>> {
    BorderColor #1ABC9C
    FontColor #0E6655
    BackgroundColor #E8F8F5
}

' Acteurs Police (Bleus)
skinparam actor<<Police>> {
    BorderColor #3498DB
    FontColor #3498DB
    BackgroundColor #EBF5FB
}
skinparam usecase<<Police>> {
    BorderColor #3498DB
    FontColor #21618C
    BackgroundColor #EBF5FB
}

' Système (Gris)
skinparam usecase<<System>> {
    BorderColor #95A5A6
    FontColor #7F8C8D
    BackgroundColor #F2F3F4
}

' --- 1. ACTEURS ---
' L'ordre ici détermine la position verticale sur le dessin (Haut -> Bas)

actor "Témoin" as Temoin <<Public>>
actor "Déclarant" as Declarant <<Public>>
' On met la VICTIME en bas du groupe public pour être proche de la notif
actor "Victime" as Victime <<Public>>

Declarant <|-- Temoin
Declarant <|-- Victime

actor "Agent Policier" as Policier <<Police>>

' --- 2. SYSTÈME ---
rectangle "Système RQV" {
    
    ' Zone Haute (Public)
    usecase "Créer une déclaration" as UC_Creer <<Public>>
    usecase "Éditer / Supprimer" as UC_Editer <<Public>>

    ' Zone Charnière (Le lien Police <-> Victime)
    usecase "Notifier les victimes" as UC_Notify <<System>>
    usecase "Gérer Objets Trouvés" as UC_Objets <<Police>>

    ' Zone Basse (Police)
    usecase "Modifier état déclaration" as UC_Update <<Police>>
    usecase "Gérer les RQV" as UC_RQV <<Police>>
    
    ' Zone Technique (Fond)
    usecase "S'authentifier" as UC_Auth <<System>>
}

' --- 3. RELATIONS ---

' Public
Declarant -- UC_Creer
Declarant -- UC_Editer

' Police
Policier -- UC_Objets
Policier -- UC_Update
Policier -- UC_RQV

' Liens Internes
' Le flux est : Police -> Objet -> Notif -> Victime
UC_Objets .> UC_Notify : <<include>>
UC_Notify --> Victime : "Alerte"

' Authentification (Tout va vers le bas)
UC_Objets ..> UC_Auth : <<include>>
UC_Update ..> UC_Auth : <<include>>
UC_RQV ..> UC_Auth : <<include>>


@enduml