@startuml
title Collaboration — Agent génère une RQV (par date)

object agent as "agent : AgentPolicier"
object gs as "gs : GestionnaireSysteme"
object rqv as "rqv : RQV"

agent -> gs : 1: sAuthentifier(matricule, motDePasse)
agent -> gs : 2: genererRQV(date)

gs -> rqv : 2.1: <<create>> RQV(date)
gs -> rqv : 2.2: calculer(declarations)

rqv -> gs : 2.3: retournerRQV()
gs -> agent : 3: rqv

@enduml
